# coding:utf-8
CHECKIN_RECORD_FIRST = 1  # 首签
CHECKIN_RECORD_AGAIN = 5  # 再签
CHECKIN_RECORD_ADD = 2  # 补签
CHECKIN_RECORD_CANCEL = 3  # 取消
CHECKIN_RECORD_END = 4  # 结束

CHECKIN_STATUS_NORMAL = 0  # 未到
CHECKIN_STATUS_SUCCESS = 1  # 正常
CHECKIN_STATUS_EARLY = 2  # 早退
CHECKIN_STATUS_LATEEARLY = 3  # 迟到早退
CHECKIN_STATUS_LATE = 4  # 迟到
CHECKIN_STATUS_ASK = 5  # 请假
CHECKIN_STATUS_CANCEL = 6  # 取消

ASK_STATUS_WAITING = 0
ASK_STATUS_APPROVE = 1
ASK_STATUS_CANCEL = 2
