# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='date',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='year',
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(db_column=b'departmentid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Department'),
        ),
        migrations.AlterField(
            model_name='course',
            name='major',
            field=models.ForeignKey(db_column=b'majorid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Major'),
        ),
        migrations.AlterField(
            model_name='course',
            name='schoolterm',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='serialnumber',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='teachclass',
            field=models.ForeignKey(db_column=b'teachclassid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Class'),
        ),
        migrations.AlterField(
            model_name='coursehomework',
            name='course',
            field=models.ForeignKey(db_column=b'courseid', on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
        migrations.AlterField(
            model_name='coursehomework',
            name='type',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='coursehomework',
            name='weight',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='course',
            field=models.ForeignKey(db_column=b'courseid', on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='uploadtime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='homeworkcommit',
            name='coursehomework',
            field=models.ForeignKey(db_column=b'coursehomeworkid', on_delete=django.db.models.deletion.CASCADE, to='course.Coursehomework'),
        ),
        migrations.AlterField(
            model_name='homeworkcommit',
            name='student',
            field=models.ForeignKey(db_column=b'studentid', on_delete=django.db.models.deletion.CASCADE, to='school.Student'),
        ),
        migrations.AlterField(
            model_name='homeworkcommit',
            name='submittime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='checkincount',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='classroom',
            field=models.ForeignKey(blank=True, db_column=b'classroomid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Classroom'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(db_column=b'courseid', on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='day',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='endtime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='length',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='starttime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='term',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='week',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='course',
            field=models.ForeignKey(db_column=b'courseid', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='course.Course'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='student',
            field=models.ForeignKey(db_column=b'studentid', on_delete=django.db.models.deletion.CASCADE, to='school.Student'),
        ),
    ]
