# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20170807_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='disable_sync',
            field=models.BooleanField(default=False),
        ),
    ]
