# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_exempt_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(db_column=b'courseid', on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
        ),
    ]
