# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_coursemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='performance_score',
            field=models.SmallIntegerField(default=0),
        ),
    ]
