# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20170807_1719'),
        ('course', '0006_studentcourse_performance_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(null=True)),
                ('endtime', models.DateTimeField(null=True)),
                ('seat', models.CharField(blank=True, max_length=4, null=True)),
                ('course', models.ForeignKey(db_column=b'courseid', on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Classroom')),
                ('student', models.ForeignKey(db_column=b'studentid', on_delete=django.db.models.deletion.CASCADE, to='school.Student')),
            ],
            options={
                'db_table': 'StudentExam',
            },
        ),
        migrations.AlterUniqueTogether(
            name='studentexam',
            unique_together=set([('student', 'course')]),
        ),
    ]
