# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20171114_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexam',
            name='course',
            field=models.ForeignKey(db_column=b'courseid', null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
    ]
