# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20171115_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='homeworkfile',
            name='file',
            field=models.FileField(upload_to=b'homeworkfile/%Y/%m/%d/'),
        ),
    ]
