# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Administration',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolyear', models.SmallIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('wechatdepartmentid', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Class',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Classroom',
            },
        ),
        migrations.CreateModel(
            name='Classtime',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('starttime', models.TimeField(blank=True, null=True)),
                ('endtime', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ClassTime',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('wechatdepartmentid', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.ForeignKey(blank=True, db_column=b'departmentid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school.Department')),
            ],
            options={
                'db_table': 'Major',
            },
        ),
        migrations.CreateModel(
            name='Schoolterm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolyear', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=20, null=True)),
                ('now', models.BooleanField(null=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SchoolTerm',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seattype', models.AutoField(primary_key=True, serialize=False)),
                ('maxnumber', models.SmallIntegerField(blank=True, null=True)),
                ('mapid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Seat',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('idnumber', models.CharField(blank=True, max_length=18, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('sex', models.SmallIntegerField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('classid', models.ForeignKey(blank=True, db_column=b'classid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school.Class')),
                ('department', models.ForeignKey(blank=True, db_column=b'departmentid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school.Department')),
                ('major', models.ForeignKey(blank=True, db_column=b'majorid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school.Major')),
                ('user', models.ForeignKey(blank=True, db_column=b'userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_system.User')),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacherid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('sex', models.SmallIntegerField(blank=True, null=True)),
                ('idnumber', models.CharField(blank=True, max_length=18, null=True)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Teacher',
            },
        ),
        migrations.CreateModel(
            name='Teachertoadministration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administration', models.ForeignKey(blank=True, db_column=b'administrationid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school.Administration')),
                ('teacher', models.ForeignKey(blank=True, db_column=b'teacherid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school.Teacher')),
            ],
            options={
                'db_table': 'TeachertoAdministration',
            },
        ),
        migrations.CreateModel(
            name='Teachertodepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(blank=True, db_column=b'departmentid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school.Department')),
                ('teacher', models.ForeignKey(blank=True, db_column=b'teacherid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school.Teacher')),
            ],
            options={
                'db_table': 'TeachertoDepartment',
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='administration',
            field=models.ManyToManyField(through='school.Teachertoadministration', to='school.Administration'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.ManyToManyField(through='school.Teachertodepartment', to='school.Department'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.ForeignKey(blank=True, db_column=b'userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_system.User'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='seattype',
            field=models.ForeignKey(blank=True, db_column=b'seattype', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school.Seat'),
        ),
        migrations.AddField(
            model_name='class',
            name='department',
            field=models.ForeignKey(blank=True, db_column=b'departmentid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school.Department'),
        ),
        migrations.AddField(
            model_name='class',
            name='major',
            field=models.ForeignKey(blank=True, db_column=b'majorid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school.Major'),
        ),
        migrations.AlterUniqueTogether(
            name='teachertodepartment',
            unique_together=set([('teacher', 'department')]),
        ),
        migrations.AlterIndexTogether(
            name='teachertoadministration',
            index_together=set([('teacher', 'administration')]),
        ),
    ]
