# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='class',
            name='department',
            field=models.ForeignKey(db_column=b'departmentid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Department'),
        ),
        migrations.AlterField(
            model_name='class',
            name='major',
            field=models.ForeignKey(db_column=b'majorid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Major'),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='class',
            name='schoolyear',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='wechatdepartmentid',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='seattype',
            field=models.ForeignKey(db_column=b'seattype', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Seat'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='wechatdepartmentid',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='major',
            name='department',
            field=models.ForeignKey(db_column=b'departmentid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Department'),
        ),
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolterm',
            name='description',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolterm',
            name='enddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schoolterm',
            name='schoolyear',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='schoolterm',
            name='startdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='seat',
            name='mapid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='maxnumber',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='classid',
            field=models.ForeignKey(db_column=b'classid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(db_column=b'departmentid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='idnumber',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.ForeignKey(db_column=b'majorid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Major'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(db_column=b'userid', null=True, on_delete=django.db.models.deletion.PROTECT, to='user_system.User'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='idnumber',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sex',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.ForeignKey(db_column=b'userid', null=True, on_delete=django.db.models.deletion.PROTECT, to='user_system.User'),
        ),
        migrations.AlterField(
            model_name='teachertoadministration',
            name='administration',
            field=models.ForeignKey(db_column=b'administrationid', on_delete=django.db.models.deletion.CASCADE, to='school.Administration'),
        ),
        migrations.AlterField(
            model_name='teachertoadministration',
            name='teacher',
            field=models.ForeignKey(db_column=b'teacherid', on_delete=django.db.models.deletion.CASCADE, to='school.Teacher'),
        ),
        migrations.AlterField(
            model_name='teachertodepartment',
            name='department',
            field=models.ForeignKey(db_column=b'departmentid', on_delete=django.db.models.deletion.CASCADE, to='school.Department'),
        ),
        migrations.AlterField(
            model_name='teachertodepartment',
            name='teacher',
            field=models.ForeignKey(db_column=b'teacherid', on_delete=django.db.models.deletion.CASCADE, to='school.Teacher'),
        ),
    ]
