# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-23 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0003_auto_20170807_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
