# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('user_system', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolterm', models.CharField(blank=True, max_length=20, null=True)),
                ('starttime', models.DateTimeField(blank=True, null=True)),
                ('endtime', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('operater', models.ForeignKey(blank=True, db_column='operater', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_system.User')),
            ],
            options={
                'db_table': 'Ask',
            },
        ),
        migrations.CreateModel(
            name='Asktostudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask', models.ForeignKey(blank=True, db_column='askid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='checkin.Ask')),
                ('student', models.ForeignKey(blank=True, db_column='studentid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school.Student')),
            ],
            options={
                'db_table': 'AsktoStudent',
            },
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.IntegerField(blank=True, db_column='seatid', null=True)),
                ('status', models.SmallIntegerField(blank=True, null=True)),
                ('laststatus', models.SmallIntegerField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('positionaccuracy', models.FloatField(blank=True, null=True)),
                ('positionlatitude', models.FloatField(blank=True, null=True)),
                ('positionlongitude', models.FloatField(blank=True, null=True)),
                ('method', models.SmallIntegerField(blank=True, null=True)),
                ('abnormal', models.SmallIntegerField(blank=True, null=True)),
                ('lesson', models.ForeignKey(blank=True, db_column='lessonid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course.Lesson')),
                ('student', models.ForeignKey(blank=True, db_column='studentid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school.Student')),
            ],
            options={
                'db_table': 'Checkin',
            },
        ),
        migrations.CreateModel(
            name='Checkinrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(blank=True, null=True)),
                ('endtime', models.DateTimeField(blank=True, null=True)),
                ('shouldnumber', models.SmallIntegerField(blank=True, null=True)),
                ('actuallynumber', models.SmallIntegerField(blank=True, null=True)),
                ('newnumber', models.SmallIntegerField(blank=True, null=True)),
                ('leavenumber', models.SmallIntegerField(blank=True, null=True)),
                ('status', models.SmallIntegerField(blank=True, null=True)),
                ('time', models.SmallIntegerField(blank=True, null=True)),
                ('lesson', models.ForeignKey(blank=True, db_column='lessonid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course.Lesson')),
            ],
            options={
                'db_table': 'CheckinRecord',
            },
        ),
        migrations.CreateModel(
            name='Scoreregulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal', models.IntegerField(default=0)),
                ('success', models.IntegerField(default=100)),
                ('early', models.IntegerField(default=30)),
                ('lateearly', models.IntegerField(default=0)),
                ('late', models.IntegerField(default=70)),
                ('private_ask', models.IntegerField(default=70)),
                ('public_ask', models.IntegerField(default=95)),
                ('course', models.ForeignKey(blank=True, db_column='courseid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course.Course')),
            ],
            options={
                'db_table': 'ScoreRegulation',
            },
        ),
        migrations.AddField(
            model_name='ask',
            name='student',
            field=models.ManyToManyField(through='checkin.Asktostudent', to='school.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='checkin',
            unique_together=set([('lesson', 'student')]),
        ),
        migrations.AlterUniqueTogether(
            name='asktostudent',
            unique_together=set([('student', 'ask')]),
        ),
    ]
