# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='endtime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ask',
            name='operater',
            field=models.ForeignKey(db_column='operater', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User'),
        ),
        migrations.AlterField(
            model_name='ask',
            name='schoolterm',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ask',
            name='starttime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ask',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ask',
            name='type',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='asktostudent',
            name='ask',
            field=models.ForeignKey(db_column='askid', on_delete=django.db.models.deletion.CASCADE, to='checkin.Ask'),
        ),
        migrations.AlterField(
            model_name='asktostudent',
            name='student',
            field=models.ForeignKey(db_column='studentid', on_delete=django.db.models.deletion.CASCADE, to='school.Student'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='abnormal',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='laststatus',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='lesson',
            field=models.ForeignKey(db_column='lessonid', on_delete=django.db.models.deletion.CASCADE, to='course.Lesson'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='method',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='positionaccuracy',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='positionlatitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='positionlongitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='student',
            field=models.ForeignKey(db_column='studentid', on_delete=django.db.models.deletion.CASCADE, to='school.Student'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='checkinrecord',
            name='actuallynumber',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='checkinrecord',
            name='endtime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='checkinrecord',
            name='leavenumber',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='checkinrecord',
            name='lesson',
            field=models.ForeignKey(db_column='lessonid', on_delete=django.db.models.deletion.CASCADE, to='course.Lesson'),
        ),
        migrations.AlterField(
            model_name='checkinrecord',
            name='newnumber',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='checkinrecord',
            name='shouldnumber',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='checkinrecord',
            name='starttime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='checkinrecord',
            name='status',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='checkinrecord',
            name='time',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='scoreregulation',
            name='course',
            field=models.ForeignKey(db_column='courseid', on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
    ]
