# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 11:57
from __future__ import unicode_literals

from django.db import migrations, models


def set_default_sick_scoure_func(apps, schema_editor):
    scoreregulation = apps.get_model("checkin", "Scoreregulation")
    db_alias = schema_editor.connection.alias
    scoreregulation.objects.using(db_alias).update(sick_ask=95)


class Migration(migrations.Migration):
    dependencies = [
        ('checkin', '0002_auto_20170807_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreregulation',
            name='sick_ask',
            field=models.IntegerField(default=95),
        ),
        migrations.RunPython(set_default_sick_scoure_func),
    ]
