# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_scoreregulation_sick_ask'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=20)),
                ('week', models.SmallIntegerField()),
                ('day', models.SmallIntegerField()),
                ('generated_time', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('course_count', models.IntegerField()),
                ('file', models.FileField(upload_to='history')),
            ],
            options={
                'db_table': 'CheckinHistory',
            },
        ),
    ]
