# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wechatkeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.SmallIntegerField(blank=True, null=True)),
                ('data', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'WechatKeyword',
            },
        ),
    ]
